name = "FixedRecurrenceArrays"
uuid = "c15e842d-fddf-409a-8e3c-800a0c0c0afd"
authors = ["Jayshiv Patel <jayshivpatel@hotmail.co.uk>"]
version = "0.1.0"

[deps]
BenchmarkPlots = "ab8c0f59-4072-4e0d-8f91-a91e1495eb26"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
RecurrenceRelationshipArrays = "b889d2dc-af3c-4820-88a8-238fa91d3518"
RecurrenceRelationships = "807425ed-42ea-44d6-a357-6771516d7b2c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
BenchmarkPlots = "0.1.0"
BenchmarkTools = "1.5.0"
MPI = "0.20.22"
PartitionedArrays = "0.5.6"
RecurrenceRelationshipArrays = "0.1.0"
RecurrenceRelationships = "0.1.0"
StatsPlots = "0.15.7"
