name = "FixedRecurrenceArrays"
uuid = "c15e842d-fddf-409a-8e3c-800a0c0c0afd"
authors = ["Jayshiv Patel <jayshivpatel@hotmail.co.uk>"]
version = "0.1.0"

[deps]
RecurrenceRelationships = "807425ed-42ea-44d6-a357-6771516d7b2c"

[compat]
RecurrenceRelationships = "0.1.0"
