name = "FixedRecurrenceArrays"
uuid = "c15e842d-fddf-409a-8e3c-800a0c0c0afd"
authors = ["Jayshiv Patel <jayshivpatel@hotmail.co.uk>"]
version = "0.1.0"

[deps]
BenchmarkPlots = "ab8c0f59-4072-4e0d-8f91-a91e1495eb26"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedData = "f6a0035f-c5ac-4ad0-b410-ad102ced35df"
RecurrenceRelationshipArrays = "b889d2dc-af3c-4820-88a8-238fa91d3518"
RecurrenceRelationships = "807425ed-42ea-44d6-a357-6771516d7b2c"

[compat]
BenchmarkPlots = "0.1.0"
BenchmarkTools = "1.5.0"
Distributed = "1.11.0"
DistributedData = "0.2.0"
RecurrenceRelationshipArrays = "0.1.0"
RecurrenceRelationships = "0.1.0"
