services:
  worker_1:
    image: julia
    build: .
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: 3.0
    ports:
      - "2222:22"
    networks:
      - app-network

  worker_2:
    image: julia
    build: .
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: 3.0
    ports:
      - "2223:22"
    networks:
      - app-network

  worker_3:
    image: julia
    build: .
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: 3.0
    ports:
      - "2224:22"
    networks:
      - app-network

  worker_4:
    image: julia
    build: .
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: 3.0
    ports:
      - "2225:22"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge