name = "FixedClenshaw"
uuid = "affd20e8-fc8d-4a62-8490-bade5c61de08"
authors = ["Jayshiv Patel"]
version = "1.0.0-DEV"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
CUDA = "5.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
